changed slow arr to make diff of 0.1 and fast arrow to 1
milosmns/actual-number-picker pull request #19
Opened 2021-04-18 11:52 UTC by Vishal0311

So i have changed the slow arrow to add or subtract 0.1 and fast arrow to add or subtract 1. 
This change can be used if like someone is creating a project and add a horizontal number picker for weight .
So he/she can slide or click the decimal number for his/her weight.

2021-04-18 12:56 UTC, milosmns requested changes
I believe that there was a misunderstanding about this change, I'll give a bit more info below.

There are live usages of this library in real projects, because of which it is not really possible to simply change the functionality the current users are used to. Upgrading to the latest version with this change could potentially break their projects.

The old behavior needs to stay the same, but can be enhanced by the new functionality using some kind of flag. What I had in mind as a potential solution (that doesn't break backwards-compatibility) is introducing a couple of flags as new View attributes:

  - `incrementArrowNormal` : `float` - how much should the **normal** arrow move the value
  - `incrementArrowFast` : `float` - how much should the **fast** arrow move the value
  - `useStaticIncrements` : `boolean` - whether to use the increments or not

With this change, `useStaticIncrements = true` could use the new attributes `incrementArrowNormal` and `incrementArrowFast` to move the value, and `useStaticIncrements = false` would keep the old behavior for the existing library users. 
Therefore, the default value of `useStaticIncrements` needs to be `false`.

Then, after implementing this in the View attributes XML and the custom View, we'd need to update the library version for Gradle, build/test on CI, and upload to jCenter (which is now deprecated), figure out how to push to MavenCentral, prepare release notes and update docs in a couple of places.

That's why I initially said that it's more effort than it seems on the surface. 🙂

And now that I think about it some more... I'm not sure if it would even be possible to push to MavenCentral directly with the current project setup, so even when code is updated - it would be difficult to distribute to end users without huge structural changes.

2021-04-18 12:56 UTC, milosmns commented on picker/src/main/java/me/angrybyte/numberpicker/view/ActualNumberPicker.java
> -        int changeX = 0;
This is change in pixels, visually, has no effect on the actual stored value.

2021-04-18 12:56 UTC, milosmns commented on picker/src/main/java/me/angrybyte/numberpicker/view/ActualNumberPicker.java
> -                changeX = (int) -(0.1f * mWidth);
This hard-codes visual movement to literally 1px, which is probably invisible to the naked eye on high-density displays.

2021-04-18 12:56 UTC, milosmns commented on picker/src/main/java/me/angrybyte/numberpicker/view/ActualNumberPicker.java
> -    private int mMinBarWidth = 1;
I think this change is unnecessary as it controls the vertical bar width and doesn't affect the X movement or the stored value.

2023-06-26 01:57 UTC, yes411 approved these changes

2023-06-26 01:57 UTC, yes411 commented on build.gradle
>      dependencies {
I

2023-06-26 01:57 UTC, yes411 commented on build.gradle
> -        classpath 'com.android.tools.build:gradle:2.3.0-beta2'
> ~~[]()[]()@jorgerego ~~

2023-06-27 12:45 UTC, milosmns commented
Either way, with JCenter shut down, I am unable to release new versions without significant code changes… for which I have no time anymore. Feel free to clone this repo and release on your own if you need the changes.

2023-06-27 12:45 UTC, closed without merging